In [3]:
#!pip install matplotlib einops seaborn tqdm torchtext==0.6.0
#!pip install --no-cache-dir torchtext==0.6.0
#!TMPDIR=/home/max/Documents/s194119/S2024/ADLCV/week1_transformers_attention/tmp_install_dir/ pip3 --cache-dir /home/max/Documents/s194119/S2024/ADLCV/week1_transformers_attention/tmp_install_dir/ install torchtext==0.6.0 einops seaborn tqdm
!TMPDIR=/home/max/Documents/s194119/S2024/ADLCV/week1_transformers_attention/tmp_install_dir/ pip3 --cache-dir /home/max/Documents/s194119/S2024/ADLCV/week1_transformers_attention/tmp_install_dir/ install einops seaborn tqdm

Defaulting to user installation because normal site-packages is not writeable
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.6/44.6 kB 6.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.9/294.9 kB 14.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.0/13.0 MB 15.1 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 505.5/505.5 kB 15.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 346.6/346.6 kB 12.4 MB/s eta 0:00:00


In [4]:
import torch
from einops import repeat, rearrange

batch_size, heigh, width = 32, 224,224
a = torch.rand((batch_size, heigh, width))


In [15]:
b = torch.Tensor([[1,0,7],[2,3,-1]])
print(b)
b1 = repeat(b, 'h w -> h w c',c=4)
print(b1)
print(b1.shape)

b1 = repeat(b, 'h w -> h c w',c=4)
print(b1)
print(b1.shape)

tensor([[ 1.,  0.,  7.],
        [ 2.,  3., -1.]])
tensor([[[ 1.,  1.,  1.,  1.],
         [ 0.,  0.,  0.,  0.],
         [ 7.,  7.,  7.,  7.]],

        [[ 2.,  2.,  2.,  2.],
         [ 3.,  3.,  3.,  3.],
         [-1., -1., -1., -1.]]])
torch.Size([2, 3, 4])
tensor([[[ 1.,  0.,  7.],
         [ 1.,  0.,  7.],
         [ 1.,  0.,  7.],
         [ 1.,  0.,  7.]],

        [[ 2.,  3., -1.],
         [ 2.,  3., -1.],
         [ 2.,  3., -1.],
         [ 2.,  3., -1.]]])
torch.Size([2, 4, 3])


In [5]:
# Increase the channels to 3
a1 = repeat(a, 'b h w -> b c h w', c=3)
print('Increase channels to 3',a1.shape)

Increase channels to 3 torch.Size([32, 3, 224, 224])


In [18]:
# Swap batch with the channels
a2 = rearrange(a1, 'b c h w -> c b h w') #just like torch.permute
print('Swap batch with the channels', a2.shape)

a2_torch = torch.permute(a1,(1,0,2,3))

torch.equal(a2,a2_torch)

Swap batch with the channels torch.Size([3, 32, 224, 224])


True

In [23]:
# Merge batch with channels
a3 = rearrange(a1, 'b c h w -> (b c) h w') #same as torch.reshape
print('Merge batch with channels', a3.shape)

a3_torch = a1.reshape(a1.shape[0]*a1.shape[1],a1.shape[2],a1.shape[-1])

torch.equal(a3,a3_torch)


Merge batch with channels torch.Size([96, 224, 224])


True

In [27]:
# Split the batch to two dimensions
a4 = rearrange(a1, '(d1 d2) c h w -> d1 d2 c h w', d1=16,d2=2)
print('Split the batch to two dimensions', a4.shape)

#equivalent to torch syntax
a4_torch = torch.unsqueeze(a1,0)
a4_torch = a4_torch.reshape(16,2,3,224,224)

torch.equal(a4_torch,a4)

Split the batch to two dimensions torch.Size([16, 2, 3, 224, 224])


True